services:
  postgres:
    profiles: ["infra"]
    image: postgres:16-alpine
    container_name: commerce-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - commerce_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U commerce -d commerce_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - commerce-net

  backend:
    profiles: ["app"]
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: commerce-backend
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

      Storage__Provider: Minio
      Storage__Endpoint: ${MINIO_ENDPOINT}
      Storage__AccessKey: ${MINIO_ACCESS_KEY}
      Storage__SecretKey: ${MINIO_SECRET_KEY}
      Storage__Bucket: ${MINIO_BUCKET}
      Storage__Region: ${MINIO_REGION}
      Storage__UseSsl: ${MINIO_USE_SSL}
      Storage__PublicBaseUrl: ${MINIO_PUBLIC_BASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      minio-init:
        condition: service_completed_successfully
    networks:
      - commerce-net

  frontend:
    profiles: ["app"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: commerce-frontend
    ports:
      - "5173:5173"
    environment:
      # Vite will use this to call the API
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    depends_on:
      - backend
    networks:
      - commerce-net

  minio:
    profiles: ["infra"]
    image: minio/minio:latest
    container_name: commerce-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - commerce_minio_data:/data
    networks:
      - commerce-net

  minio-init:
    profiles: ["infra"]
    image: minio/mc:latest
    container_name: commerce-minio-init
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        echo 'Waiting for MinIO...'; sleep 2;
      done &&
      mc mb -p local/${MINIO_BUCKET} || true &&
      mc anonymous set download local/${MINIO_BUCKET} || true
      "
    networks:
      - commerce-net

networks:
  commerce-net:
    driver: bridge

volumes:
  commerce_pgdata:
  commerce_minio_data:
